<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upload_file</name>
   <tag></tag>
   <elementGuidId>12b4c0e7-ab28-421e-ac61-61d995195f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'file' and @id = 'thumbnailAdd']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;thumbnailAdd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18efa170-f7b5-4c19-a00a-d274f19ba26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7004bd98-5140-4b8c-9738-df2591c7d4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thumbnailAdd</value>
      <webElementGuid>44e933a1-aae9-4140-8803-34c18192870c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
